export const LOADING_TRUE = "LOADING_TRUE";
export const LOADING_FALSE = "LOADING_FALSE";
export const PROGRESS_LOADING_TRUE = "PROGRESS_LOADING_TRUE";
export const PROGRESS_LOADING_FALSE = "PROGRESS_LOADING_FALSE";